# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias vi='vim'

alias ls='ls --color=tty'
alias la='ls -lAh'
alias ll='ls -lh'

#export TERM=xterm-256color
#force_color_promt=yes
export NODE_MIRROR=https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Launch Zsh
if [ -t 1  ]; then
    exec zsh
fi
