# macOS library
#export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/usr/local/opt/mysql-client/lib:$DYLD_LIBRARY_PATH

export PATH=$PATH:$HOME/bin:/usr/local/mysql/bin:/usr/local/opt/mysql-client/bin

# run 'brew install openssh' first
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm

if [ $commands[qshell] ]; then
  source <(qshell completion zsh)
fi
