# bashrc.d/bashrc ext profile

setopt no_nomatch

export VISUAL="vim"
export TERM=xterm-color

alias w='w -i'

# vim or neovim , this is a question
if type nvim > /dev/null 2>&1; then
    alias vim='nvim'
    alias vi='nvim'
else
    alias vi='vim'
fi

# For Linux
if [ `uname` = 'Linux' ]; then
    source ~/.dotfiles/bashrc.d/linux/bashrc
fi

# For macOS
if [ `uname` = 'Darwin' ]; then
    source ~/.dotfiles/bashrc.d/macos/bashrc
fi

# For nvm setting
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# For user
if [ -f ~/.profile_user  ]; then
    source ~/.profile_user
fi

