# bashrc.d/bashrc ext profile

setopt no_nomatch

export VISUAL="vim"
export TERM=xterm-color

alias w='w -i'
alias dc=docker-compose
alias sail='bash vendor/bin/sail'

# vim or neovim , this is a question
if type nvim > /dev/null 2>&1; then
    alias vim='nvim'
    alias vi='nvim'
else
    alias vi='vim'
fi

export PATH=$PATH:$HOME/.bin:$HOME/.composer/vendor/bin:/usr/local/go/bin

# golang env
if type go > /dev/null 2>&1; then
    source ~/.dotfiles/bashrc.d/goenv.sh
fi

# For macOS
if [ $OSTYPE = "darwin"* ]; then
    source ~/.dotfiles/bashrc.d/macos.sh
fi

# For user
if [ -f ~/.profile_user  ]; then
    source ~/.profile_user
fi

