# bashrc.d/bashrc ext profile

setopt no_nomatch

alias w='w -i'

if type nvim > /dev/null 2>&1; then
    alias vim='nvim'
    alias vi='nvim'
else
    alias vi='vim'
fi

export GOPATH=~/go
export VISUAL="vim"
export TERM=xterm-color
export NODE_MIRROR=https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/
export PATH=$PATH:$HOME/.bin

# For Linux
if [ `uname` = 'Linux' ]; then
    source ~/.dotfiles/bashrc.d/linux/bashrc
fi

# For macOS
if [ `uname` = 'Darwin' ]; then
    source ~/.dotfiles/bashrc.d/macos/bashrc
fi

# For user
if [ -f ~/.profile  ]; then
    source ~/.profile
fi
